#!/usr/bin/env python3
import json 

win_dict = {}
mac_dict = {}
std_dict = {}
pdf_dict = {}

while True:
        try:
                l = input().split()
                std_dict[l[2]] = {'c': l[0], 'name': l[1]}
                mac_dict[l[3]] = {'c': l[0], 'name': l[1]}
                win_dict[l[4]] = {'c': l[0], 'name': l[1]}
                pdf_dict[l[5]] = {'c': l[0], 'name': l[1]}
        except EOFError:
                break
        
l = [ ('std', std_dict), ('mac', mac_dict), ('win', win_dict), ('pdf', pdf_dict)]

for n, d in l:
        with open(f'{n}-encoding.json', 'w') as f:
                json.dump(d, f)
